-- Create table Wines
DROP TABLE Wines IF EXISTS;
CREATE TABLE Wines (nom VARCHAR(200), couleur VARCHAR(50), region VARCHAR(100), appellation VARCHAR(200), millesime VARCHAR(10), pays VARCHAR(100));
-- Insert Wines
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Sociando-Mallet', 'Rouge', 'Bordeaux', 'Haut-Médoc', '2000', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château La Pointe', 'Rouge', 'Bordeaux', 'Pomerol', '2000', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Meursault-Charmes 1er Cru - Domaine des Comtes Lafon', 'Blanc', 'Bourgogne', 'Meursault-Charmes', '2000', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Échezeaux Grand Cru - Frédéric Magnien', 'Rouge', 'Bourgogne', 'Échezeaux', '2000', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Grand Millésime - Gosset', 'Blanc effervescent', 'Champagne', 'Champagne', '2000', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('LBV Port - Jose Maria Da Fonseca', 'Rouge fortifié', 'Duriense', 'Porto', '2000', 'Portugal');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Pavillon Blanc du Château Margaux', 'Blanc', 'Bordeaux', 'Bordeaux', '1996', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château de Fieuzal', 'Blanc', 'Bordeaux', 'Pessac-Léognan', '1996', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Léoville Las Cases', 'Rouge', 'Bordeaux', 'Saint-Julien', '1996', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Haut-Bailly', 'Rouge', 'Bordeaux', 'Pessac-Léognan', '1996', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Hospices de Nuits - Les Terres Blanches', 'Rouge', 'Bourgogne', 'Nuits-Saint-Georges', '1996', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Côteau de Noiré', 'Rouge', 'Loire', 'Chinon', '1996', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Egly-Ouriet Blanc de Noirs', 'Blanc effervescent', 'Champagne', 'Champagne', 'N.M', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Mouton Rothschild', 'Rouge', 'Bordeaux', 'Pauillac', '1992', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Haut-Brion', 'Rouge', 'Bordeaux', 'Pessac-Léognan', '1991', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('La Landonne - E. Guigual', 'Rouge', 'Rhône', 'Côte-Rôtie', '1994', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Pontet-Canet', 'Rouge', 'Bordeaux', 'Pauillac', '1990', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Barberac - M. Chapoutier', 'Rouge', 'Rhône', 'Châteauneuf-Du-Pape', '1993', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Le Haut-Lieu - Huet', 'Blanc liquoreux', 'Loire', 'Vouvray', '1989', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Domaine de Trévallon', 'Rouge', 'Provence', 'Vin de Pays des Bouches du Rhône', '1999', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('La Grande Année', 'Blanc effervescent', 'Champagne', 'Champagne', '1999', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Mazis-Chambertin Grand Cru - Maison Champy', 'Rouge', 'Bourgogne', 'Mazis-Chambertin', '1999', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Gruaud-Larose', 'Rouge', 'Bordeaux', 'Saint-Julien', '1999', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Clos des Lambrays', 'Rouge', 'Bourgogne', 'Morey-Saint-Denis', '1999', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Montus - Cuvée prestige', 'Rouge', 'Sud-Ouest', 'Madiran', '1999', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Marojallia', 'Rouge', 'Bordeaux', 'Margaux', '1999', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Masburel', 'Blanc', 'Sud-Ouest', 'Montravel', '2001', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Aile d''Argent - Château Mouton Rothschild', 'Blanc', 'Bordeaux', 'Bordeaux', '2001', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Domaine de Trévallon', 'Rouge', 'Provence', 'Vin de Pays des Bouches du Rhône', '2001', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Pavie', 'Rouge', 'Bordeaux', 'Saint-Émilion-Grand-Cru', '2001', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Les Grandes Places - Domaine Clusel-Roch', 'Rouge', 'Rhône', 'Côte-Rôtie', '2001', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Chambolle-Musigny 1er Cru Les Amoureuses - Domaine Amiot-Servelle', 'Rouge', 'Bourgogne', 'Chambolle-Musigny', '2001', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Domaine du Clos des Fées Vieilles Vignes', 'Rouge', 'Roussillon', 'Côtes du Roussillon Villages', '2001', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Clos Häuserer - Riesling - Domaine Zind Humbrecht', 'Blanc', 'Alsace', 'Alsace', '2004', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('C... du Prieur', 'Rouge', 'Languedoc-Roussillon', 'Coteaux-du-Languedoc', '2003', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Crozes Hermitage "Cuvée Albéric Bouvet" - Gilles Robin', 'Rouge', 'Rhône', 'Crozes-Hermitage', '2002', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Trotanoy', 'Rouge', 'Bordeaux', 'Pomerol', '1997', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château La Mission Haut-Brion', 'Rouge', 'Bordeaux', 'Pessac-Léognan', '1999', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Muscat Vendanges Tardives Altenbourg - Albert Mann', 'Blanc liquoreux', 'Alsace', 'Alsace', '2001', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Simone', 'Rosé', 'Provence', 'Palette', '2009', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Krug', 'Blanc effervescent', 'Champagne', 'Champagne', '1988', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Montrachet Grand Cru - Domaines du Château de Beaune - Bouchard Père et Fils', 'Blanc', 'Bourgogne', 'Montrachet', '1986', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Sociando-Mallet', 'Rouge', 'Bordeaux', 'Haut-Médoc', '1983', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Lynch-Bages', 'Rouge', 'Bordeaux', 'Pauillac', '1983', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Latour', 'Rouge', 'Bordeaux', 'Pauillac', '1985', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Léoville Poyferré', 'Rouge', 'Bordeaux', 'Saint-Julien', '1983', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Labégorce Zédé', 'Rouge', 'Bordeaux', 'Margaux', '1989', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Nuits Saint Georges 1er cru Clos de l''Arlot - Domaine de l''Arlot', 'Blanc', 'Bourgogne', 'Nuits-Saint-Georges', '2004', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Rayas', 'Blanc', 'Rhône', 'Châteauneuf-Du-Pape', '2004', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Montrose', 'Rouge', 'Bordeaux', 'Saint-Estèphe', '2004', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château de Beaucastel', 'Rouge', 'Rhône', 'Châteauneuf-Du-Pape', '2004', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Lurumea - Domaine Bordatto', 'Rouge', 'Sud-Ouest', 'Irouléguy', '2004', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Domaine de l''A', 'Rouge', 'Bordeaux', 'Castillon-Côtes-de-Bordeaux', '2004', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Catena Zapata Malbec Argentino', 'Rouge', 'Mendoza', '-', '2004', 'Argentine');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Anthologia - Château Tour Des Gendres - Famille De Conti', 'Blanc', 'Sud-Ouest', 'Bergerac sec', '2001', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Haut Bages Libéral', 'Rouge', 'Bordeaux', 'Pauillac', '1981', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Chambolle-Musigny - Confrérie des Chevaliers du Tastevin', 'Rouge', 'Bourgogne', 'Chambolle-Musigny', '1967', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Clos des Jacobins', 'Rouge', 'Bordeaux', 'Saint-Émilion-Grand-Cru', '1979', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Nénin', 'Rouge', 'Bordeaux', 'Pomerol', '1978', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Chambolle-Musigny Charmes - Morin Père et Fils', 'Rouge', 'Bourgogne', 'Chambolle-Musigny', '1959', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Haut-Brion', 'Rouge', 'Bordeaux', 'Pessac-Léognan', '1976', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château des Rochettes - Sélection de Grains Nobles', 'Blanc liquoreux', 'Loire', 'Coteaux du Layon', '1989', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Pécany - Cuvée Spéciale', 'Blanc liquoreux', 'Sud-Ouest', 'Monbazillac', '1976', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Mas de Daumas Gassac', 'Rouge', 'Languedoc-Roussillon', 'Vin de Pays de l''Hérault', '1998', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Clos Sainte-Hune - Riesling - Trimbach', 'Blanc', 'Alsace', 'Alsace', '2002', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Brézé - Clos Rougeard', 'Blanc', 'Loire', 'Saumur', '2003', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Prieuré-Lichine', 'Rouge', 'Bordeaux', 'Margaux', '2004', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Pontet-Canet', 'Rouge', 'Bordeaux', 'Pauillac', '1990', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château La Fleur-Pétrus', 'Rouge', 'Bordeaux', 'Pomerol', '1990', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château d''Yquem', 'Blanc liquoreux', 'Bordeaux', 'Sauternes', '1998', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Dom Pérignon', 'Blanc effervescent', 'Champagne', 'Champagne', '1996', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Clos Sainte-Hune - Riesling - Trimbach', 'Blanc', 'Alsace', 'Alsace', '2003', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Corton-Charlemagne Grand Cru - Dufouleur Père et Fils', 'Blanc', 'Bourgogne', 'Corton-Charlemagne', '2003', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Bâtard-Montrachet Grand Cru - Bouchard Père et Fils', 'Blanc', 'Bourgogne', 'Bâtard-Montrachet', '2003', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Poujeaux', 'Rouge', 'Bordeaux', 'Moulis-en-Médoc', '2003', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Vosne-Romanée Malconsorts - Louis Jadot', 'Rouge', 'Bourgogne', 'Vosne-Romanée', '2003', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Les Eygats - Domaine Courbis', 'Rouge', 'Rhône', 'Cornas', '2003', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('L''Icône - Château de Sérame', 'Rouge', 'Languedoc-Roussillon', 'Corbières', '2003', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Minuty - Rosé Prestige', 'Rosé', 'Provence', 'Côtes de Provence', '2011', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Clos de La Coulée de Serrant', 'Blanc', 'Loire', 'Savennières-Coulée-De-Serrant', '2006', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Domaine Gauby Blanc - Vielles Vignes', 'Blanc', 'Languedoc-Roussillon', 'Vin de Pays des Côtes Catalanes', '2009', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Ambonnay Rouge Vielles Vignes - Cuvée des Grands Côtés - Egly Ouriet', 'Rouge', 'Champagne', 'Coteaux Champenois', '2009', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Hermitage - Jean-Louis Chave', 'Rouge', 'Rhône', 'Hermitage', '2002', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Prieuré de Saint-Jean de Bébian', 'Rouge', 'Languedoc-Roussillon', 'Languedoc', '2001', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château-Chalon', 'Blanc', 'Jura', 'Château-Chalon', '1989', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Le Pech Badin', 'Rouge', 'Sud-Ouest', 'Vin de table', '2005', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Terroirs de Quintaine - Jean-Pierre Michel', 'Blanc', 'Bourgogne', 'Viré-Clessé', '2010', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Mas de Daumas Gassac', 'Blanc', 'Languedoc-Roussillon', 'Vin de Pays de l''Hérault', '2009', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Carbonnieux', 'Blanc', 'Bordeaux', 'Pessac-Léognan', '2006', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Ermitage de L''Orée - M. Chapoutier', 'Blanc', 'Rhône', 'Hermitage', '2005', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Clerc Milon', 'Rouge', 'Bordeaux', 'Pauillac', '1982', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Lagrange', 'Rouge', 'Bordeaux', 'Saint-Julien', '1998', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Romanée-Saint-Vivant - Domaine de La Romanée Conti', 'Rouge', 'Bourgogne', 'Romanée-Saint-Vivant', '1996', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Krug grande cuvée brut', 'Blanc effervescent', 'Champagne', 'Champagne', 'N.M', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Criots-Bâtard-Montrachet Grand Cru - Louis Latour', 'Blanc', 'Bourgogne', 'Criots-Bâtard-Montrachet', '2001', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Échezeaux Grand Cru - J-P Mugneret', 'Rouge', 'Bourgogne', 'Échezeaux', '1996', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Branaire (Duluc - Ducru)', 'Rouge', 'Bordeaux', 'Saint-Julien', '1996', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Les Forts de Latour', 'Rouge', 'Bordeaux', 'Pauillac', '1998', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Pavillon Rouge de Château Margaux', 'Rouge', 'Bordeaux', 'Margaux', '1998', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Anthologia - Château Tour Des Gendres - Famille De Conti', 'Rouge', 'Sud-Ouest', 'Bergerac', '2000', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Champagne Rosé Laurent-Perrier', 'Rosé effervescent', 'Champagne', 'Champagne', 'N.M', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Ducru Beaucaillou', 'Rouge', 'Bordeaux', 'Saint-Julien', '1921', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Gruaud Larose', 'Rouge', 'Bordeaux', 'Saint-Julien', '1942', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Les Granits - M. Chapoutier', 'Blanc', 'Rhône', 'Saint-Joseph', '2001', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Gruaud Larose', 'Rouge', 'Bordeaux', 'Saint-Julien', '1967', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château des Coulinats - Cuvée Réservée', 'Blanc liquoreux', 'Bordeaux', 'Sainte-Croix-Du-Mont', '1955', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Châteauneuf du Pape Cuvée Marie Beurrier - Henri Bonneau', 'Rouge', 'Rhône', 'Châteauneuf-Du-Pape', '1988', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Gilette - Crème de tête', 'Blanc liquoreux', 'Bordeaux', 'Sauternes', '1976', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Trotanoy', 'Rouge', 'Bordeaux', 'Pomerol', '1990', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château d''Epiré - Cuvée Spéciale', 'Blanc', 'Loire', 'Savennières', '2010', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Champagne Rosé - Louis Roederer', 'Rosé effervescent', 'Champagne', 'Champagne', '2007', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Pur Sang - Didier Dagueneau', 'Blanc', 'Loire', 'Pouilly-Fumé', '2007', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Caillou Blanc - Château Talbot', 'Blanc', 'Bordeaux', 'Bordeaux', '2007', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Griotte-Chambertin - Domaine Ponsot', 'Rouge', 'Bourgogne', 'Griotte-Chambertin', '2007', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Pinot noir Le Grand H - Albert Mann', 'Rouge', 'Alsace', 'Alsace', '2007', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Côte-Rôtie La Mouline - E. Guigal', 'Rouge', 'Rhône', 'Côte-Rôtie', '2007', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Les Noëls de Montbenault - Richard Leroy', 'Blanc', 'Loire', 'Vin de France', '2010', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('La Grande Dame - Veuve Cliquot Ponsardin', 'Blanc effervescent', 'Champagne', 'Champagne', '1990', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Chassagne-Montrachet 1er Cru - Louis Latour', 'Blanc', 'Bourgogne', 'Chassagne-Montrachet', '2002', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Longueville du Baron de Pichon-Longueville', 'Rouge', 'Bordeaux', 'Pauillac', '1979', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Pavie', 'Rouge', 'Bordeaux', 'Saint-Émilion-Grand-Cru', '1989', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Carruades de Lafite', 'Rouge', 'Bordeaux', 'Pauillac', '2001', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Domaine du Pélican - Vendages Tardives', 'Blanc liquoreux', 'Loire', 'Anjou-Coteaux-de-la-Loire', '2007', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Taburnum - Les Vins de Vienne', 'Blanc', 'Rhône', 'Vin de Pays des Collines Rhodaniennes', '2008', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Les Terrasses de l''Empire - Domaine Georges Vernay', 'Blanc', 'Rhône', 'Condrieu', '2011', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Renaissance - Domaine Clape', 'Rouge', 'Rhône', 'Cornas', '2000', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Aventure - Domaine Mas Saint Joseph', 'Rouge', 'Rhône', 'Costières de Nîmes', '2009', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Châteauneuf du Pape - Domaine Raymond Usseglio & Fils', 'Rouge', 'Rhône', 'Châteauneuf-Du-Pape', '2000', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('D''Eux - Séguret - Domaine de Cabasse', 'Rouge', 'Rhône', 'Côtes-du-Rhône-Villages', '2006', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Banyuls Grand Cru - Vignerons Catalans', 'Rouge fortifié', 'Rhône', 'Banyuls Grand Cru', '2003', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château La Grande Clotte', 'Blanc', 'Bordeaux', 'Bordeaux', '2009', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Le Bon Pasteur', 'Rouge', 'Bordeaux', 'Pomerol', '2006', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Lynsolence', 'Rouge', 'Bordeaux', 'Saint-Émilion-Grand-Cru', '2006', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Fontenil', 'Rouge', 'Bordeaux', 'Fronsac', '2009', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château de la Rivière', 'Rouge', 'Bordeaux', 'Fronsac', '2009', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Le Défi de Fontenil', 'Rouge', 'Bordeaux', 'Vin de table', '2000', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Clos de los Siete', 'Rouge', 'Mendoza', '-', '2009', 'Argentine');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Clos Häuserer - Riesling - Domaine Zind Humbrecht', 'Blanc', 'Alsace', 'Alsace', '2009', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Mont-Redon - Blanc de Blancs', 'Blanc', 'Rhône', 'Châteauneuf-Du-Pape', '2001', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Dom Pérignon', 'Blanc effervescent', 'Champagne', 'Champagne', '2000', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Rauzan-Ségla', 'Rouge', 'Bordeaux', 'Margaux', '1996', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('La Chapelle de Sainte Roseline', 'Rouge', 'Provence', 'Côtes de Provence', '2006', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Gloria', 'Rouge', 'Bordeaux', 'Saint-Julien', '1989', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château de Fesles', 'Blanc liquoreux', 'Loire', 'Bonnezeaux', '?', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Bulles de Syrah - Brut Nature "Blanc de Noirs" - Jean-Louis Denois - Vignoble des Fenouillèdes', 'Blanc effervescent', 'Languedoc-Roussillon', 'Vin de Pays des Coteaux des Fenouillèdes', 'N.M', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Domaine de la Courtade (Porquerolles)', 'Rouge', 'Provence', 'Côtes de Provence', '2006', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Échezeaux Grand Cru - Domaine des Perdrix', 'Rouge', 'Bourgogne', 'Échezeaux', '2006', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Chateau d''Aiguilhe', 'Rouge', 'Bordeaux', 'Castillon-Côtes-de-Bordeaux', '2006', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Corton-Charlemagne Grand Cru - Olivier Leflaive', 'Blanc', 'Bourgogne', 'Corton-Charlemagne', '2006', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Kayoumi Single Vineyard Shiraz - Carmel winery', 'Rouge', 'Galilée', '-', '2006', 'Israël');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Les Fées Brunes - Jean-Luc Colombo', 'Rouge', 'Rhône', 'Crozes-Hermitage', '2006', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Bonnes-Mares Grand Cru - Domaione Drouhin-Laroze', 'Rouge', 'Bourgogne', 'Bonnes-Mares', '2006', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Cuvée Capatas - Domaine du Traginer', 'Rouge', 'Languedoc-Roussillon', 'Collioure', '2006', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Victoire - Nicolas Reau', 'Blanc', 'Loire', 'Anjou', '2010', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Salon Blanc de Blancs', 'Blanc effervescent', 'Champagne', 'Champagne', '1997', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Savennières Trie Spéciale - Domaine des Baumards', 'Blanc', 'Loire', 'Savennières', '1995', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Nenin', 'Rouge', 'Bordeaux', 'Pomerol', '1995', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Branaire (Duluc - Ducru)', 'Rouge', 'Bordeaux', 'Saint-Julien', '1996', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Phélan Ségur', 'Rouge', 'Bordeaux', 'Saint-Estèphe', '1982', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Clos Saint Landelin - Pinot gris Vendanges Tardives - René Muré', 'Blanc liquoreux', 'Alsace', 'Alsace-Grand-Cru', '1998', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Vouvray - Méthode Traditionnelle - Claude Moine', 'Blanc effervescent', 'Loire', 'Vouvray', 'N.M', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Caillottes - François Cotat', 'Blanc', 'Loire', 'Sancerre', '2009', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Pavillon Blanc de Château Margaux', 'Blanc', 'Bordeaux', 'Bordeaux', '2008', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Clos Joliette', 'Blanc liquoreux', 'Sud-Ouest', 'Jurançon', '1986', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Finca Altamira - Malbec - Achaval-Ferrer', 'Rouge', 'Mendoza', '-', '2005', 'Argentine');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Franc de Pied - Bernard Baudry', 'Rouge', 'Loire', 'Chinon', '2009', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Gaillard - Domaine de Fond Chatonne', 'Rouge', 'Beaujolais', 'Morgon', '2010', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Cos Labory', 'Rouge', 'Bordeaux', 'Saint-Estèphe', '2005', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Lagrange', 'Rouge', 'Bordeaux', 'Saint-Julien', '2005', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Lagrange', 'Rouge', 'Bordeaux', 'Saint-Julien', '1996', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Pontet-Canet', 'Rouge', 'Bordeaux', 'Pauillac', '1996', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Lagrange', 'Rouge', 'Bordeaux', 'Saint-Julien', '2000', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Le Bon Pasteur', 'Rouge', 'Bordeaux', 'Pomerol', '2000', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Rémus - Domaine de la Taille aux Loups - Jacky Blot', 'Blanc', 'Loire', 'Montlouis-Sur-Loire', '2001', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Buisson Renard - Didier Dagueneau', 'Blanc', 'Loire', 'Pouilly-Fumé', '2007', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Blanc Fumé de Pouilly - Didier Dagueneau', 'Blanc', 'Loire', 'Pouilly-Fumé', '2004', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Les Varennes du Grand Clos - Charles Joguet', 'Rouge', 'Loire', 'Chinon', '2002', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Chinon Vieilles Vignes - Philippe Alliet', 'Rouge', 'Loire', 'Chinon', '2005', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château de Fesles', 'Blanc liquoreux', 'Loire', 'Bonnezeaux', '?', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Quarts de Chaume - Domaine des Baumards', 'Blanc liquoreux', 'Loire', 'Quarts-De-Chaume', '1994', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Viognier - Les Vins de Vienne', 'Blanc', 'Rhône', 'Vin de France', '2013', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Clos de la Coulée de Serrant', 'Blanc', 'Loire', 'Savennières-Coulée-De-Serrant', '2000', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Clos des Mouches - Joseph Drouhin', 'Blanc', 'Bourgogne', 'Beaune', '2000', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Lagrange', 'Rouge', 'Bordeaux', 'Saint-Julien', '2000', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Châteauneuf du Pape - Domaine Raymond Usseglio & Fils', 'Rouge', 'Rhône', 'Châteauneuf-Du-Pape', '2000', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Léoville Las Cases', 'Rouge', 'Bordeaux', 'Saint-Julien', '2000', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Muscat de Beaumes de Venise - Réserve J. Vidal-Fleury', 'Blanc liquoreux', 'Rhône', 'Muscat-De-Beaumes-De-Venise', '2000', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Grande Réserve - Gosset', 'Blanc effervescent', 'Champagne', 'Champagne', 'N.M', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Domaine de Trévallon', 'Blanc', 'Provence', 'Vin de Pays des Alpilles', '2009', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Charmes-Chambertin - Frédéric Magnien', 'Rouge', 'Bourgogne', 'Charmes-Chambertin', '2005', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Léoville Barton', 'Rouge', 'Bordeaux', 'Saint-Julien', '2005', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Montrose', 'Rouge', 'Bordeaux', 'Saint-Estèphe', '1998', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Célébris - Vintage Extra Brut - Gosset', 'Blanc effervescent', 'Champagne', 'Champagne', '2002', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Le Blanc du Château Prieuré-Lichine', 'Blanc', 'Bordeaux', 'Bordeaux', '2005', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Les Grandes Places - Domaine Clusel-Roch', 'Rouge', 'Rhône', 'Côte-Rôtie', '2005', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Le Puy - Cuvée Barthélemy', 'Rouge', 'Bordeaux', 'Côtes de Francs', '2005', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Trotte Vieille', 'Rouge', 'Bordeaux', 'Saint-Émilion', '2005', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Mambourg', 'Blanc', 'Alsace', 'Alsace-Grand-Cru', '2005', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Chadonnay - Domaine La Petite Forge - Daniel et Katrin Pabion', 'Blanc', 'Loire', 'Vin de Pays des Côtes-de-la-charité', '2013', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Mas de Daumas Gassac', 'Blanc', 'Languedoc-Roussillon', 'Vin de Pays de l''Hérault', '2009', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Cuvée 6 de Coeur - Domaine de Pierre Belle', 'Rouge', 'Languedoc-Roussillon', 'Vin de Pays des Coteaux du Libron', '2009', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Le Sang des Volcans - Syrah', 'Rouge', 'Loire', 'Puy-De-Dôme', '2012', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Une et Mille Nuits - Domaine Canet Valette', 'Rouge', 'Languedoc-Roussillon', 'Saint-Chinian', '2006', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Rabaud-Promis', 'Blanc liquoreux', 'Bordeaux', 'Sauternes', '1995', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Champagne Royale Réserve Non Dosé - Philipponnat', 'Blanc effervescent', 'Champagne', 'Champagne', 'N.M', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Clochers De Coustaussa - Sieur d''Arques', 'Blanc', 'Languedoc-Roussillon', 'Limoux', '2012', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Franc de Pied - Bernard Baudry', 'Rouge', 'Loire', 'Chinon', '2009', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Cos d''Estournel', 'Rouge', 'Bordeaux', 'Saint-Estèphe', '2001', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Gevrey-Chambertin Vigne Belle - Domaine Thierry Mortet', 'Rouge', 'Bourgogne', 'Gevrey-Chambertin', '2011', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Chablis - Domaine Fourrey', 'Blanc', 'Bourgogne', 'Chablis', '2014', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Nuits Saint Georges 1er cru Clos de l''Arlot - Domaine de l''Arlot', 'Blanc', 'Bourgogne', 'Nuits-Saint-Georges', '2009', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Morey-Saint-Denis 1er Cru Les Faconnières - Domaine Marchand Frères', 'Rouge', 'Bourgogne', 'Morey-Saint-Denis', '2012', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Angélus', 'Rouge', 'Bordeaux', 'Saint-Émilion-Grand-Cru', '2002', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('La Chapelle de Sainte Roseline', 'Rouge', 'Provence', 'Côtes de Provence', '2006', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Clos Saint Urbain - Gewurztraminer - Rangen de Thann - Domaine Zind Humbrecht', 'Blanc', 'Alsace', 'Alsace-Grand-Cru', '2009', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Egly-Ouriet - Brut Grand Cru', 'Blanc effervescent', 'Champagne', 'Champagne', '1996', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Clos de Tart', 'Rouge', 'Bourgogne', 'Clos-de-Tart', '2007', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château La Voulte-Gasparet', 'Rouge', 'Languedoc-Roussillon', 'Corbières', '2007', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Monier de la Sizeranne - M. Chapoutier', 'Rouge', 'Rhône', 'Hermitage', '2009', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Ausone', 'Rouge', 'Bordeaux', 'Saint-Émilion-Grand-Cru', '1988', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Haut-Brion', 'Rouge', 'Bordeaux', 'Pessac-Léognan', '2004', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Pontet-Canet', 'Rouge', 'Bordeaux', 'Pauillac', '1982', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Folle Blanche - Pierre Luneau-Papin', 'Blanc', 'Loire', 'Gros Plant du Pays Nantais', '2014', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Champagne Brut Nature édition limitée by Philippe Starck - Louis Roederer', 'Blanc effervescent', 'Champagne', 'Champagne', '2006', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Châteauneuf du Pape - Domaine Raymond Usseglio & Fils', 'Blanc', 'Rhône', 'Châteauneuf-Du-Pape', '2006', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Nuits Saint Georges 1er cru Clos de l''Arlot - Domaine de l''Arlot', 'Rouge', 'Bourgogne', 'Nuits-Saint-Georges', '2006', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Clos René', 'Rouge', 'Bordeaux', 'Pomerol', '2006', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Domaine de la Grange des Pères', 'Rouge', 'Languedoc-Roussillon', 'Vin de Pays de l''Hérault', '2006', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Champagne Brut Nature - Pinot Noir Zéro Dosage - Drappier', 'Blanc effervescent', 'Champagne', 'Champagne', 'N.M', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Silex - Didier Dagueneau', 'Blanc', 'Loire', 'Pouilly-Fumé', '2007', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Les Chaillées de l''Enfer - Domaine Georges Vernay', 'Blanc', 'Rhône', 'Condrieu', '2007', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Le Petit Mouton de Mouton Rothschild', 'Rouge', 'Bordeaux', 'Pauillac', '2007', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Cos d''Estournel', 'Rouge', 'Bordeaux', 'Saint-Estèphe', '2007', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Cuvée Folie - Sélection de Grains Nobles - Château des Rochettes', 'Blanc liquoreux', 'Loire', 'Coteaux du Layon', '2010', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Il Vino "Dal Tralcetto" - Cantina Zaccagnini', 'Rouge', 'Abruzzes', 'Montepulciano d''Abruzzo', '2015', 'Italie');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Le K - Ampelidae', 'Rouge', 'Loire', 'Vin de Pays de la Vienne', '2000', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Clos Boucher - Delas', 'Blanc', 'Rhône', 'Condrieu', '2007', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Riesling - Cuvée Clément - Domaine Stirn', 'Blanc', 'Alsace', 'Alsace-Grand-Cru', '2004', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Lagrange', 'Rouge', 'Bordeaux', 'Saint-Julien', '1983', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Le Clos Guillot - Bernard Baudry', 'Rouge', 'Loire', 'Chinon', '2013', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Cristal Rosé - Louis Roederer', 'Rosé effervescent', 'Champagne', 'Champagne', '2005', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Clos Jebsal - Pinot Gris Vendanges Tardives - Domaine Zind Humbrecht', 'Blanc liquoreux', 'Alsace', 'Alsace-Grand-Cru', '2005', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Le L d''Or - Domaine Luneau-Papin', 'Blanc', 'Loire', 'Muscadet Sèvre et Maine', '2005', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Riesling Muenchberg - Domaine Ostertag', 'Blanc', 'Alsace', 'Alsace-Grand-Cru', '2008', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Condrieu - Mathilde et Yves Gangloff', 'Blanc', 'Rhône', 'Condrieu', '2008', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Morey-Saint-Denis 1er Cru Clos Sorbé - Maison Gille', 'Rouge', 'Bourgogne', 'Morey-Saint-Denis', '2008', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Hermitage - Jean-Louis Chave', 'Rouge', 'Rhône', 'Hermitage', '2008', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Rieussec', 'Blanc liquoreux', 'Bordeaux', 'Sauternes', '2008', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Champagne Jacquesson Extra Brut', 'Blanc effervescent', 'Champagne', 'Champagne', '2005', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Brézé - Clos Rougeard', 'Blanc', 'Loire', 'Saumur', '2005', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Clos des Lunelles', 'Rouge', 'Bordeaux', 'Castillon-Côtes-de-Bordeaux', '2005', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Pichon-Longueville du Baron de Pichon-Longueville', 'Rouge', 'Bordeaux', 'Pauillac', '2005', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Sociando-Mallet', 'Rouge', 'Bordeaux', 'Haut-Médoc', '2005', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Reserve Shiraz Viognier - Yering Station', 'Rouge', 'Yarra Valley', '-', '2005', 'Australie');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château de Rayne Vigneau', 'Blanc liquoreux', 'Bordeaux', 'Sauternes', '2005', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Cuvée des Loups - Domaine de la Taille aux Loups - Jacky Blot', 'Blanc liquoreux', 'Loire', 'Montlouis-Sur-Loire', '2005', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Champagne Belle Époque - Perrier-Jouët', 'Blanc effervescent', 'Champagne', 'Champagne', '1995', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château d''Issan', 'Rouge', 'Bordeaux', 'Margaux', '1996', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Lynch-Bages', 'Rouge', 'Bordeaux', 'Pauillac', '1990', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Dow''s Vintage Port', 'Rouge fortifié', 'Duriense', 'Porto', '1997', 'Portugal');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Les Cailloux - Cuvée Centenaire', 'Rouge', 'Rhône', 'Châteauneuf-Du-Pape', '1989', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Champagne Brut - Pur Pinot Noir - Cuvée Grande Réserve - Jean-Luc Carreau', 'Blanc effervescent', 'Champagne', 'Champagne', 'N.M', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Hermitage - Tardieu-Laurent', 'Blanc', 'Rhône', 'Hermitage', '2005', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Les Terrasses de l''Empire - Domaine Georges Vernay', 'Blanc', 'Rhône', 'Condrieu', '2011', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Les Grandes Places - Domaine Clusel-Roch', 'Rouge', 'Rhône', 'Côte-Rôtie', '2011', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('La Turque - E. Guigal', 'Rouge', 'Rhône', 'Côte-Rôtie', '2007', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château de Beaucastel', 'Rouge', 'Rhône', 'Châteauneuf-Du-Pape', '2003', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Sainte-Épine - Delas', 'Rouge', 'Rhône', 'Saint-Joseph', '2013', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Chablis 1er Cru "La Forest" - Vincent Dauvissat', 'Blanc', 'Bourgogne', 'Chablis', '2008', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Champagne Belle Époque - Perrier-Jouët', 'Blanc effervescent', 'Champagne', 'Champagne', '2008', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Puligny-Montrachet 1er Cru Les Combettes - Domaine J.M. Boillot', 'Blanc', 'Bourgogne', 'Puligny-Montrachet', '2002', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Nouvelle Terre - Chardonnay - Daniel Mouty', 'Blanc', 'Bordeaux', 'Vin de France', '2016', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Egly-Ouriet - Brut Rosé Grand Cru', 'Rosé effervescent', 'Champagne', 'Champagne', 'N.M', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Sancerre Charlouise - Vincent Pinard', 'Rouge', 'Loire', 'Sancerre', '?', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Chapelle-Chambertin Grand Cru - Domaine Trapet Père et Fils', 'Rouge', 'Bourgogne', 'Chapelle-Chambertin', '1995', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Sancerre La Moussière - Alphonse Mellot', 'Rouge', 'Loire', 'Sancerre', '2009', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Volnay 1er Cru Santenots du Milieu - Domaine des Comtes Lafon', 'Rouge', 'Bourgogne', 'Volnay', '1999', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Pinot noir Le Grand H - Albert Mann', 'Rouge', 'Alsace', 'Alsace', '2007', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('P.N. 1328 - Ampelidae', 'Rouge', 'Loire', 'Vin de Pays de la Vienne', '2005', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Dézaley Grand Cru - Pierre-Luc Leyvraz', 'Blanc', 'Vaud', 'Dézaley Grand Cru', '2017', 'Suisse');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Champagne Brut Nature - Pinot Noir Zéro Dosage - Drappier', 'Blanc effervescent', 'Champagne', 'Champagne', 'N.M', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Aile d''Argent - Château Mouton Rothschild', 'Blanc', 'Bordeaux', 'Bordeaux', '2005', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Pontet-Canet', 'Rouge', 'Bordeaux', 'Pauillac', '2005', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Hermitage La Chapelle - Paul Jaboulet Ainé', 'Rouge', 'Rhône', 'Hermitage', '2005', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Les Pyeux - Clos Rougeard', 'Rouge', 'Loire', 'Saumur-Champigny', '2005', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Léoville Poyferré', 'Rouge', 'Bordeaux', 'Saint-Julien', '2005', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château de Rayne Vigneau', 'Blanc liquoreux', 'Bordeaux', 'Sauternes', '2005', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Auxey-Duresses - Pierre Taupenot', 'Blanc', 'Bourgogne', 'Auxey-Duresses', '1994', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Rémus - Domaine de la Taille aux Loups - Jacky Blot', 'Blanc', 'Loire', 'Montlouis-Sur-Loire', '1999', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Hermitage - Jean-Louis Chave', 'Blanc', 'Rhône', 'Hermitage', '1995', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Pape Clément', 'Rouge', 'Bordeaux', 'Pessac-Léognan', '1995', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Pontet-Canet', 'Rouge', 'Bordeaux', 'Pauillac', '1990', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Ducru Beaucaillou', 'Rouge', 'Bordeaux', 'Saint-Julien', '1993', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Sélection de Grains Nobles - Cuvée Sophie - Château des Rochettes', 'Blanc liquoreux', 'Loire', 'Coteaux du Layon', '1998', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('L''Ancestrale - Domaine Vincent Carême', 'Blanc effervescent', 'Loire', 'Vouvray', '2015', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Méthode Ancestrale - Domaines des Terres Blanches - Céline et Benoît Blet', 'Blanc effervescent', 'Loire', 'Vin de France', '2017', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Les Monts Damnés - François Cotat', 'Blanc', 'Loire', 'Sancerre', '2002', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Les Rouliers - Richard Leroy', 'Blanc', 'Loire', 'Vin de France', '2011', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Brézé - Clos Rougeard', 'Blanc', 'Loire', 'Saumur', '2003', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Clos de la Coulée de Serrant', 'Blanc', 'Loire', 'Savennières-Coulée-De-Serrant', '2001', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('La Charpentrie - Domaine du Collier', 'Rouge', 'Loire', 'Saumur', '2012', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Busardières - Domaine de la Chevalerie', 'Rouge', 'Loire', 'Bourgueil', '2005', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Chinon Vieilles Vignes - Philippe Alliet', 'Rouge', 'Loire', 'Chinon', '2005', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Chinon Coteau de Noiré - Philippe Alliet', 'Rouge', 'Loire', 'Chinon', '2009', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Quarts de Chaume - Domaine des Baumards', 'Blanc liquoreux', 'Loire', 'Quarts-De-Chaume', '1997', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Clos du Bourg - Domaine Huet', 'Blanc liquoreux', 'Loire', 'Vouvray', '1989', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Bugey Cerdon - Méthode Ancestrale - Bernard et Marjorie Rondeau', 'Rosé effervescent', 'Savoie', 'Bugey Cerdon', 'N.M', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('La Chandella - Bernard et Marjorie Rondeau', 'Rosé effervescent', 'Savoie', 'Vin de France', 'N.M', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Beaune 1er Cru - Domaine Baptiste Guyot', 'Rouge', 'Bourgogne', 'Beaune', '2014', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Beaune 1er Cru "Clos des Avaux" - Domaine Baptiste Guyot', 'Rouge', 'Bourgogne', 'Beaune', '2016', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Beaune 1er Cru "Les Teurons" - Domaine Baptiste Guyot', 'Rouge', 'Bourgogne', 'Beaune', '2017', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Volnay 1er Cru - Domaine Baptiste Guyot', 'Rouge', 'Bourgogne', 'Volnay', '2016', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Nuits Saint Georges - Domaine Pillot-Henry', 'Rouge', 'Bourgogne', 'Nuits-Saint-Georges', '?', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Pommard 1er Cru "Les Charmots" - Domaine Pillot-Henry', 'Rouge', 'Bourgogne', 'Pommard', '?', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Le Blanc - Clos des Figuiers', 'Blanc', 'Sud-Ouest', 'Côtes-de-Duras', '2015', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Gevrey-Chambertin - Domaine Berthaut-Gerbet', 'Rouge', 'Bourgogne', 'Gevrey-Chambertin', '2016', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Chardonnay - Domaine Bellegarde', 'Blanc', 'Languedoc-Roussillon', 'Limoux', '2016', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('L''Enfant Terrible - Nicolas Reau', 'Rouge', 'Loire', 'Anjou', '2010', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Dézaley Grand Cru - Domaine Antoine Bovard', 'Blanc', 'Vaud', 'Dézaley Grand Cru', '2015', 'Suisse');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Le Mont - Domaine Huet', 'Blanc liquoreux', 'Loire', 'Vouvray', '2009', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Savigny-lès-Beaune 1er Cru "Aux Vergelesses" - Château Génot-Boulanger', 'Blanc', 'Bourgogne', 'Savigny-Lès-Beaune', '2009', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Le Clos Blanc de Vougeot - Domaine de la Vougeraie', 'Blanc', 'Bourgogne', 'Vougeot', '2012', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Champagne Grand Siècle - Laurent-Perrier', 'Blanc effervescent', 'Champagne', 'Champagne', 'N.M', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Côte-Rotie - Domaine Clusel-Roch', 'Rouge', 'Rhône', 'Côte-Rôtie', '2006', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Mouton Rothschild', 'Rouge', 'Bordeaux', 'Pauillac', '2004', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Gewurztraminer Vendanges Tardives - Clos Saint-Théobald - Grand Cru Rangen - Domaine Schoffit', 'Blanc liquoreux', 'Alsace', 'Alsace-Grand-Cru', '2001', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Clos de la Coulée de Serrant', 'Blanc', 'Loire', 'Savennières-Coulée-De-Serrant', '2015', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Clos des Lambrays', 'Rouge', 'Bourgogne', 'Morey-Saint-Denis', '2009', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Château Pape Clément', 'Rouge', 'Bordeaux', 'Pessac-Léognan', '2009', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Vin de Paille - François Mossu', 'Blanc liquoreux', 'Jura', 'Côtes-du-Jura', '2010', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Albariño - Selección de Añada - Pazo de Señoráns', 'Blanc', 'Rías Baixas', '-', '2011', 'Espagne');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Sur Le Mont - Domaine Cheveau', 'Blanc', 'Bourgogne', 'Mâcon-Solutré-Pouilly', '2018', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Grenache Blanc Vieilles Vignes - Domaine du Clos des Fées', 'Blanc', 'Languedoc-Roussillon', 'Vin de Pays des Côtes Catalanes', '2011', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Du Chaos naît une Étoile - Bertrand et Vincent Marchesseau', 'Rouge', 'Loire', 'Vin de table', '2016', 'France');
INSERT INTO Wines(nom, couleur, region, appellation, millesime, pays) VALUES ('Sante Victoire - Château Coussin', 'Rouge', 'Provence', 'Côtes de Provence', '2007', 'France');